# Generated by Django 3.0 on 2022-04-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('email', models.EmailField(default='youremailisrequired', max_length=255, unique=True, verbose_name='email address')),
                ('ip_address', models.CharField(default='ABC', max_length=120)),
                ('mobile', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('gender', models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=15)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Manager'), (2, 'Realtor')], null=True)),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('is_realtor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
