# Generated by Django 3.0 on 2022-04-07 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0002_auto_20220406_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='mobile',
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=500)),
                ('state_of_origin', models.CharField(default='', max_length=500)),
                ('account_merchant', models.CharField(default='', max_length=500)),
                ('account_number', models.CharField(default='', max_length=500)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('gender', models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=15)),
                ('realtor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
