# Generated by Django 3.0 on 2022-04-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0003_auto_20220407_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='account_number',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
