# Generated by Django 3.0 on 2022-04-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0004_auto_20220409_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='referral_code',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='RealtorDownline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150, unique=True)),
                ('mobile', models.CharField(default='', max_length=13, unique=True)),
                ('referral_code', models.CharField(default='', max_length=40, unique=True)),
                ('realtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdapp.Realtor')),
            ],
        ),
    ]
