# Generated by Django 3.0 on 2022-04-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0005_auto_20220411_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='referral_code',
        ),
        migrations.DeleteModel(
            name='RealtorDownline',
        ),
    ]
