# Generated by Django 3.0 on 2022-04-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0007_auto_20220411_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtordownline',
            name='referral_code',
            field=models.CharField(default='', max_length=40),
        ),
    ]
