# Generated by Django 3.0 on 2022-04-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0008_auto_20220412_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media/properties')),
                ('property_id', models.CharField(default='', max_length=50)),
                ('property_type', models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=15)),
                ('location', models.CharField(default='', max_length=500)),
                ('no_of_unit_or_plot', models.PositiveSmallIntegerField(default=0)),
                ('price_per_unit_plot', models.CharField(default='', max_length=15)),
                ('on_promo', models.BooleanField(default=False)),
                ('promo_price_per_unit_or_plot', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoldProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=500)),
                ('property_id', models.CharField(default='', max_length=50)),
                ('property_type', models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=15)),
                ('location', models.CharField(default='', max_length=500)),
                ('no_of_unit_or_plot', models.PositiveSmallIntegerField(default=0)),
                ('price_per_unit_plot', models.CharField(default='', max_length=15)),
                ('on_promo', models.BooleanField(default=False)),
                ('promo_price_per_unit_or_plot', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_reward_percentage', models.PositiveSmallIntegerField(blank=True, choices=[(1, '15'), (2, '3')], null=True)),
                ('fifteen_percent_unit', models.PositiveSmallIntegerField(default=0)),
                ('three_percent_unit', models.PositiveSmallIntegerField(default=0)),
                ('realtor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdapp.Realtor')),
            ],
        ),
    ]
