# Generated by Django 3.0 on 2022-04-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0010_property_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowSelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media/properties')),
                ('property_type', models.CharField(choices=[('None', 'None'), ('Land', 'Land'), ('Buildings', 'Buildings')], default='None', max_length=15)),
                ('location', models.CharField(default='', max_length=500)),
                ('unit_of_plot', models.PositiveSmallIntegerField(default=0)),
                ('price_per_unit_plot', models.CharField(default='', max_length=15)),
                ('on_promo', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('promo_price_per_unit_or_plot', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('None', 'None'), ('Land', 'Land'), ('Buildings', 'Buildings')], default='None', max_length=15),
        ),
    ]
