# Generated by Django 3.0 on 2022-04-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0011_auto_20220430_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
