# Generated by Django 3.0 on 2022-04-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0012_auto_20220430_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowselling',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
