# Generated by Django 3.0 on 2022-04-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0013_nowselling_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowselling',
            name='title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
