# Generated by Django 3.0 on 2022-05-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0014_nowselling_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealtorDownline',
            new_name='RealtorClient',
        ),
        migrations.AddField(
            model_name='realtor',
            name='referral',
            field=models.CharField(default='', max_length=50),
        ),
    ]
