# Generated by Django 3.0 on 2022-06-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0016_auto_20220501_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowselling',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='referral',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
