# Generated by Django 3.0 on 2022-06-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0017_auto_20220601_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='media/properties/videos'),
        ),
    ]
