# Generated by Django 3.0 on 2022-06-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0023_auto_20220630_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
