# Generated by Django 3.0 on 2022-06-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0024_auto_20220630_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='ip_address',
            field=models.CharField(default='21.0.0.1', max_length=120),
        ),
    ]
