# Generated by Django 3.0 on 2022-06-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0025_auto_20220630_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
