# Generated by Django 3.0 on 2022-06-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0026_myuser_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
    ]
