# Generated by Django 3.0 on 2022-06-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0029_auto_20220630_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
