# Generated by Django 3.0 on 2022-06-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0030_remove_myuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='newuser@goldenland.ng', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='ip_address',
            field=models.CharField(default='ABC', max_length=120),
        ),
    ]
