# Generated by Django 3.0 on 2022-06-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0031_auto_20220630_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
