# Generated by Django 3.0 on 2022-06-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0032_myuser_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
