# Generated by Django 3.0 on 2022-06-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0033_auto_20220630_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
    ]
