# Generated by Django 3.0 on 2022-06-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdapp', '0034_remove_myuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
